### ISSUE TITLE
NameError: name 'AdAccount' is not defined

### ISSUE THREAD

**Issue by groott** [facebook/facebook-python-business-sdk#364]
Hi,
I can't get sample code to work. I updated imports but still I get:

> Traceback (most recent call last):
  File "test.py", line 34, in <module>
    my_account = AdAccount.get_my_account()
NameError: name 'AdAccount' is not defined

```
from facebookads.session import FacebookSession
from facebookads import FacebookAdsApi
from facebookads.adobjects.helpers import *
from facebookads.adobjects import *

import ad_creation_utils
import json
import os

this_dir = os.path.dirname(__file__)
config_filename = os.path.join(this_dir, 'config.json')

config_file = open(config_filename)
config = json.load(config_file)
config_file.close()

### Setup session and api objects
session = FacebookSession(
    config['app_id'],
    config['app_secret'],
    config['access_token'],
)
api = FacebookAdsApi(session)

if __name__ == '__main__':
    FacebookAdsApi.set_default_api(api)

    # Get my account (first account associated with the user associated with the
    #                 session of the default api)
    my_account = AdAccount.get_my_account()

    print('**** Creating ad...')

    # Create my ad
    my_ad = ad_creation_utils.create_website_clicks_ad(
        account=my_account,

        name="Visit Seattle",
        country='US',

        title="Visit Seattle",                             # How it looks
        body="Beautiful Puget Sound.",
        url="http://www.seattle.gov/visiting/",
        image_path=os.path.join(
            os.path.dirname(__file__),
            os.pardir,
            'image.png'
        ),

        bid_type=AdSet.BidType.cpm,
        bid_info={AdSet.Field.BidInfo.impressions: 53},  # $0.53 / thousand
        daily_budget=1000,  # $10.00 per day

        age_min=13,
        age_max=65,

        paused=True,  # Default is False but let's keep this test ad paused
    )
    print('**** Done!')

    # Get the preview and write an html file
    preview = my_ad.get_ad_preview(params={
        AdPreview.Field.ad_format: AdPreview.AdFormat.right_column_standard
    })
    preview_filename = os.path.join(this_dir, 'preview_ad.html')
    preview_file = open(preview_filename, 'w')
    preview_file.write(
        "<html><head><title>Facebook Ad Preview</title><body>%s</body></html>"
        % preview.get_html()
    )
    preview_file.close()
    print('**** %s has been created!' % preview_filename)
```

**Comment by scottydelta** [comment]
No where on your code `AdAccount` is defined/imported and that is why you are getting the error. You need to import it before using it. You can import it by putting this line at the top of your code:

`from facebookads.adobjects.adaccount import AdAccount`

**Comment by TityBoi** [comment]
Ok thanks now I think imported all I needed but now I get:

> **** Creating ad...
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    bid_type=AdSet.BidType.cpm,
AttributeError: type object 'AdSet' has no attribute 'BidType'

```
from facebookads.adobjects.adaccount import AdAccount
from facebookads.adobjects.adset import AdSet
from facebookads.adobjects.ad import Ad
from facebookads.session import FacebookSession
from facebookads import FacebookAdsApi
from facebookads.adobjects.helpers import *
from facebookads.adobjects import *
```

**Comment by scottydelta** [comment]
@TityBoi Please post this question on [stackoverflow](stackoverflow.com) as it is more suited there. This forum is intended for reporting bugs and issues within the code library. Thanks

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
