### ISSUE TITLE
Delete Users From Custom Audience: Broken Pipe error

### ISSUE THREAD

**Issue by Olof-n** [facebook/facebook-python-business-sdk#367]
I'm having the exact same issue as described in https://github.com/facebook/facebook-python-ads-sdk/issues/279. However, I'm getting it even when sending only ~2,500 entries. If I go below 2,000 it seems fine. Somewhere in between I get back a 400 response with: 
```
Facebook | Error - Sorry, something went wrong. We're working on it and we'll get it fixed as soon as we can.
```

According to the documentation https://developers.facebook.com/docs/marketing-api/reference/custom-audience/users/, it should support 10,000 entries?

```
Traceback (most recent call last):
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/luigi/worker.py", line 129, in _run_get_new_deps
    task_gen = self.task.run()
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/transdictor/transdictor_task.py", line 263, in run
    self.execute()
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/transdictor/egestors/facebook/tasks.py", line 141, in execute
    emails_to_remove)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/transdictor/egestors/facebook/custom_audience_submitter.py", line 121, in submit_emails
    audience.remove_users(CustomAudience.Schema.email_hash, batched_emails_to_remove)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/facebookads/adobjects/helpers/customaudiencemixin.py", line 229, in remove_users
    pre_hashed,
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/facebookads/api.py", line 305, in call
    timeout=self._session.timeout
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/olofnilsson/projects/growth/analytics/transdictor/venv/lib/python3.6/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

**Comment by Olof-n** [comment]
The payload in `customaudiencemixin.py` looks legit:
`
{'schema': 'EMAIL_SHA256', 'is_raw': False, 'data': ['9681439ac9cde9f2e2f69ef0aec6420e726546cf3f744544fe1c49320fc94622', '684ddd3dd0197ae7cbedf5f64336a97925d5baaf2ba139f05782b26ee222075e',
.
.
.
'6b94feee1d890ba4ce4a94827f4531122cb662c5c6e3575eae9f7e7f3e63339c']}
`

**Comment by jkehler** [comment]
I seem to be encountering this problem as well. If i go below 2000 entries it's fine.

**Comment by tosolveit** [comment]
Same issue, over 1500 I get the same error :(

**Comment by emetselaar** [comment]
I do something like this now to cut the upload in pieces. Maybe it helps someone struggling with this

`
def chunker(seq, size):
    return (seq[pos:pos + size] for pos in xrange(0, len(seq), size))
`

and in the code that adds the audience I use that function that makes chunks

`    
for group in chunker(users, 1000):
        audienceId.add_users(scheme, group, pre_hashed=True)
`

**Comment by mikhaildubov** [comment]
Same issue here.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
